# Generated by Django 4.1.5 on 2023-02-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busqueda',
            old_name='producto',
            new_name='elemento',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='producto',
            new_name='elemento',
        ),
    ]
